export const vietqrBanks = [
  { code: "VCB", name: "Vietcombank" },
  { code: "TCB", name: "Techcombank" },
  { code: "VPB", name: "VPBank" },
  { code: "BIDV", name: "BIDV" },
  { code: "VIB", name: "VIB" },
  { code: "MBB", name: "MB Bank" },
  { code: "ACB", name: "ACB" },
  { code: "HDB", name: "HDBank" },
  { code: "TPB", name: "TPBank" },
  { code: "STB", name: "Sacombank" },
  { code: "SHB", name: "SHB" },
  { code: "EIB", name: "Eximbank" },
  { code: "SCB", name: "SCB" },
  { code: "OCB", name: "OCB" },
  { code: "LPB", name: "LienVietPostBank" },
  { code: "MSB", name: "MSB" },
  { code: "ABB", name: "ABBank" },
  { code: "BVB", name: "BVB" },
  { code: "CBB", name: "CBBank" },
  { code: "PGB", name: "PG Bank" },
  { code: "SGB", name: "SaigonBank" },
  { code: "KLB", name: "KienlongBank" },
  { code: "VAB", name: "VietABank" },
  { code: "SEA", name: "SeABank" },
  { code: "BAOVIET", name: "BaoVietBank" },
  { code: "NAMABANK", name: "NamABank" },
  { code: "NCB", name: "NCB" },
  { code: "PVCOM", name: "PVcomBank" },
  { code: "GPB", name: "GPBank" },
  { code: "VID", name: "VID Public Bank" }
];
